<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net10.0-windows</TargetFramework>
        <RootNamespace>CV2_Modding_Framework_UI</RootNamespace>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
        <ApplicationManifest>app.manifest</ApplicationManifest>
        <ApplicationIcon>Resources\Icon.ico</ApplicationIcon>
        <Company>KittySkin</Company>
        <Product>CV2 Modding Framework</Product>
        <Version>3.0.0</Version>
        <IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
        <Configurations>Debug;Release;Debug About;Debug Setup Module</Configurations>
        <Platforms>AnyCPU</Platforms>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug About' ">
      <OutputPath>bin\Debug\</OutputPath>
      <DebugSymbols>true</DebugSymbols>
    </PropertyGroup>

    <PropertyGroup Condition=" '$(Configuration)' == 'Debug Setup Module' ">
      <OutputPath>bin\Debug\</OutputPath>
      <DebugSymbols>true</DebugSymbols>
    </PropertyGroup>

    <ItemGroup>
      <Compile Update="UI\About.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="UI\AddNewModUi.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="UI\SetupModule.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="UI\Game Files Comparison.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="UI\DownloadLinks.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="UI\EditModUi.cs">
        <SubType>Form</SubType>
      </Compile>
      <Compile Update="UI\ActiveModContentViewer.cs">
        <SubType>Form</SubType>
      </Compile>
    </ItemGroup>

    <ItemGroup>
      <None Include="folder_structure.json">
        <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
      </None>
    </ItemGroup>

    <ItemGroup>
      <Folder Include="HelperScripts\" />
      <Folder Include="Resources\" />
    </ItemGroup>

    <ItemGroup>
        <None Include="HelperScripts\CompareGameFiles.bat">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
    <ItemGroup>
        <None Include="Resources\CV2.usmap">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
    </ItemGroup>
</Project>